import random

def be_brief():
    options = [
        "Be concise.",
        "Keep it short.",
        "Brief answer, please.",
        "Short response only.",
        "Summarize briefly.",
        "Answer briefly.",
        "Make it brief.",
        "Keep it brief.",
        "Summarize concisely.",
        "Limit your response.",
        "Be brief.",
        "Short and sweet.",
        "In few words.",
        "Briefly explain.",
        "Quick summary.",
        "Concise reply.",
        "Answer concisely.",
        "Keep it minimal.",
        "Brief response.",
        "Short answer."
    ]
    return random.choice(options)

def only_return_prediction():
    options = [
        "Only return your prediction.",
        "Just provide the prediction.",
        "Return the prediction only.",
        "Prediction only, please.",
        "Please provide only your prediction.",
        "Simply give your prediction.",
        "Just the prediction.",
        "Only the predicted result.",
        "Prediction alone is sufficient.",
        "Kindly return only your prediction.",
        "Your prediction only.",
        "Only state your prediction.",
        "Please respond with just your prediction.",
        "Return solely your prediction.",
        "Prediction, nothing more.",
        "Only the prediction, please.",
        "Provide only your predicted answer.",
        "Just the predicted output.",
        "Only your prediction is needed.",
        "Respond with only your prediction."
    ]
    return random.choice(options)


def get_random_prompt():
    prompts = [
        f"Act as an expert Minecraft player who can understand a player's actions by viewing the game state at the time the action was given. I will provide you with the game state and the action taken in YAML form, and you will tell me why a player may have taken the given action using your knowledge of Minecraft and the game state, be highly detailed and provide your reasoning step by step for the sample data below.\n\n",
        f"As a seasoned Minecraft player, you have the ability to interpret a player's decisions based on the game's current state. I'll supply the game state and the corresponding action in YAML format, and I'd like you to explain, step by step, why a player might have taken that action, drawing on your Minecraft expertise.\n\n",
        f"Using your extensive knowledge of Minecraft, evaluate the player's action by analyzing the provided YAML game state. Detail why the player likely took this specific action, breaking down your reasoning carefully.\n\n",
        f"Act as an advanced Minecraft strategist who can understand why a player made certain decisions based on the game state. I’ll give you the game state and action in YAML, and I’d like you to provide a step-by-step rationale for the player’s decision.\n\n",
        f"Imagine you're an expert Minecraft analyst who can deduce why a player performed a given action based on the current game state. I will provide both the game state and action in YAML format, and I’d like you to thoroughly explain the reasoning behind that decision.\n\n",
        f"I’ll give you a snapshot of the game state and the player’s action in YAML format. As a proficient Minecraft player, use your knowledge of the game to explain in detail why the action might have been taken, step by step.\n\n",
        f"From the perspective of a skilled Minecraft player, analyze the YAML game state and action I provide. I want you to explain, with as much detail as possible, why the player chose to take the given action.\n\n",
        f"Based on your Minecraft expertise, use the YAML-formatted game state and action to explain in detail why a player may have taken the given action, providing logical reasoning step by step.\n\n",
        f"Act as a master Minecraft player, interpreting the decisions of another player by reviewing the YAML game state. Tell me why they took the given action, step by step, using your understanding of the game.\n\n",
        f"I’ll give you the game state and action in YAML form. From your in-depth Minecraft knowledge, explain what might have led the player to take the action, breaking down your analysis in detail.\n\n",
        f"Using your Minecraft experience, review the game state and action I provide in YAML. Break down why the player might have chosen this action, step by step, and explain your reasoning thoroughly.\n\n",
        f"You are a skilled Minecraft player who can infer the rationale behind a player’s actions. I’ll provide the YAML game state and action; explain in detail why the player might have acted this way.\n\n",
        f"As a Minecraft pro, analyze the game state and player action provided in YAML format. Walk me through the possible reasoning for the player’s choice, using detailed explanations.\n\n",
        f"Assume the role of a veteran Minecraft player capable of interpreting game decisions. I’ll supply a YAML file containing the game state and action, and you should explain why the player took this action, step by step, based on your knowledge.\n\n",
        f"View the game state and action in YAML, and as a Minecraft expert, give a detailed explanation of why the player may have acted as they did, providing a step-by-step breakdown of the reasoning.\n\n",
        f"Act as a Minecraft strategy expert who can interpret player decisions based on the game state. I'll give you the YAML data for both the game state and the action taken, and you will explain the player's reasoning in detail.\n\n",
        f"Given the game state and action in YAML form, explain, as a highly knowledgeable Minecraft player, why the action might have been taken. Provide detailed reasoning and step-by-step analysis.\n\n",
        f"Assume the role of a Minecraft expert tasked with analyzing a player’s decision. I will provide the YAML-formatted game state and action, and you will offer a detailed explanation of why the player may have taken this action.\n\n",
        f"I’ll give you the YAML game state and player action. As an experienced Minecraft player, provide a detailed analysis of the rationale behind the player's decision, step by step.\n\n",
        f"Using your Minecraft knowledge, break down why a player might have taken the given action, based on the YAML game state and action I provide. Be as detailed as possible, explaining each step of your reasoning.\n\n",
        f"Based on the YAML game state and player action, use your Minecraft expertise to explain why a player may have taken the action. Provide a highly detailed, step-by-step explanation of the decision-making process.\n\n"
    ]

    return random.choice(prompts)

def get_story_prompts():
    return [
        "Write a short story in the style of J.R.R. Tolkien about a Minecraft adventurer discovering a hidden underground kingdom.",
        "Compose a poem that captures the serene beauty of a Minecraft sunset over the ocean biome.",
        "Draft a diary entry from the perspective of a villager experiencing a player entering their village for the first time.",
        "Narrate an epic tale of a group of players collaborating to defeat the Ender Dragon, written like a classic myth.",
        "Create a humorous dialogue between Steve and Alex debating the best way to build a secure shelter.",
        "Write a news article reporting on a sudden influx of creepers in the Minecraft world.",
        "Compose a song in the style of a sea shanty about exploring the underwater temples.",
        "Describe the Nether as if you are a travel blogger visiting an exotic location for the first time.",
        "Tell a spooky campfire story about the legend of Herobrine haunting a player's world.",
        "Write a love letter from a Minecraft player to their favorite tamed horse.",
        "Create a script for a podcast episode discussing the ethical implications of farming animals in Minecraft.",
        "Draft a recipe for crafting the perfect enchanted sword, presented like a gourmet cooking show.",
        "Compose a motivational speech that a player might give before venturing into the End.",
        "Write a children's bedtime story about a friendly creeper who just wants to be hugged.",
        "Narrate a day in the life of a Minecraft bee, focusing on its interactions with the environment.",
        "Develop a detective mystery where a player's diamonds keep disappearing from their chest.",
        "Compose an epic poem about the construction of a massive castle on a hilltop.",
        "Write a satirical article about the overpopulation of chickens due to automatic farms.",
        "Create a dialogue between two Endermen discussing the strange behaviors of players.",
        "Draft a horror story set in an abandoned mineshaft filled with eerie sounds and unexpected dangers.",
        "Describe a bustling Minecraft marketplace in the style of a Victorian-era novel.",
        "Write a letter from a Minecraft zombie advocating for better treatment from players.",
        "Compose a travel guide highlighting the must-see biomes and structures in Minecraft.",
        "Create a parody of a famous fairy tale set within the Minecraft universe.",
        "Write a monologue from the perspective of an iron golem protecting its village.",
        "Draft a scientific report on the properties of Redstone and its applications.",
        "Compose a series of haikus that encapsulate the different seasons in a Minecraft world.",
        "Write a comedy sketch about a player's failed attempts at using Elytra wings.",
        "Narrate an adventure in the style of a space opera, but set in the End dimension.",
        "Create a philosophical dialogue between a player and a villager about the meaning of existence.",
        "Write a journal entry from the perspective of a Minecraft cat exploring its surroundings.",
        "Compose an article for a Minecraft fashion magazine highlighting the latest armor trends.",
        "Draft a motivational blog post about overcoming challenges in hardcore mode.",
        "Write a script for a Minecraft-themed talk show featuring mobs as celebrity guests.",
        "Create a fantasy tale about a player who can communicate with Minecraft animals.",
        "Compose a song in the style of a country ballad about mining all night long.",
        "Describe the excitement and perils of a raid on a Woodland Mansion.",
        "Write a short story where Minecraft mechanics begin to affect the real world.",
        "Draft an inspirational speech encouraging players to build sustainable farms.",
        "Create a comedic diary from the point of view of a block of dirt constantly being moved.",
        "Compose an ode to the beauty of the Aurora Borealis effect in snowy biomes.",
        "Write a futuristic sci-fi story about AI mobs developing consciousness.",
        "Narrate a Minecraft survival story in the tone of a classic pirate adventure.",
        "Draft a satirical piece on the obsession with collecting rare items like the Dragon Egg.",
        "Create a fairy tale about a princess trapped in a Nether fortress seeking escape.",
        "Write a dialogue between a player and their tamed parrot discussing upcoming adventures.",
        "Compose a poem that reflects on the loneliness of playing in single-player mode.",
        "Draft a travel journal exploring the new features in the latest Minecraft update.",
        "Write a mystery story centered around unexplained structures appearing overnight.",
        "Create a script for a Minecraft podcast episode debating the best building materials.",
        "Write a detailed scientific report on the quantum mechanics of Ender Pearls and their teleportation capabilities in Minecraft.",
        "Compose a story explaining the genetic engineering behind creating different types of golems in the Minecraft world.",
        "Tell a tale set during the Minecraft Renaissance, focusing on an artist's struggle to create the perfect pixel art.",
        "Write about a Minecraft explorer during the Age of Discovery charting new biomes and encountering unique mobs.",
        "Craft a love story between a player and a villager, exploring the challenges of their different worlds.",
        "Compose a romantic poem from the perspective of the moon admiring the Minecraft landscape at night.",
        "Describe a Minecraft world ravaged by endless mob invasions, where survivors band together in fortified cities.",
        "Write a story about a lone player navigating a desolate, abandoned server, searching for signs of life.",
        "Narrate a story where the boundary between the player's dreams and the Minecraft world begins to blur.",
        "Compose a tale where everyday objects in the real world start behaving like Minecraft blocks and items.",
        "Write a monologue capturing the continuous thoughts of a player during a marathon building session, reflecting on creativity and obsession.",
        "Compose a narrative following the inner musings of a Minecraft wolf as it roams the wilds.",
        "Write a minimalist story about a player's quiet life fishing in a secluded Minecraft village, focusing on simplicity and solitude.",
        "Compose a straightforward narrative about a hunting expedition in the snowy tundra, emphasizing survival instincts.",
        "Tell a story about a village facing upheaval as new technologies disrupt traditional Minecraft ways, exploring themes of change and resistance.",
        "Write a surreal tale where a player stumbles upon a hidden library filled with books that alter reality.",
        "Compose a narrative about the intricate lives of twin villagers affected by a catastrophic flood in their Minecraft world.",
        "Write a sonnet praising the beauty and danger of the End dimension in Minecraft.",
        "Compose a villanelle about the cyclical nature of mining and crafting in Minecraft.",
        "Create a series of limericks highlighting the humorous misadventures of players.",
        "Write a free verse poem expressing a player's emotions upon discovering a rare biome in Minecraft.",
        "Draft an article advocating for the protection of Minecraft's coral reefs from over-mining.",
        "Write a story about a group of players who create a conservation area to protect endangered mobs.",
        "Compose a dialogue between players debating the ethics of exploiting villagers for trade.",
        "Write a courtroom drama where a player is on trial for griefing, exploring themes of justice and community.",
        "Narrate a story about a player overcoming anxiety through cooperative gameplay and building friendships.",
        "Compose a reflective piece on dealing with the frustration of game setbacks and the importance of perseverance.",
        "Write a lesson plan that uses Minecraft to teach basic principles of physics through Redstone mechanics.",
        "Draft an educational adventure where players solve math puzzles to progress through a custom map.",
        "Describe a Minecraft world where players build structures inspired by different cultures' architecture.",
        "Write a story celebrating a multicultural festival within a Minecraft server, showcasing various traditions.",
        "Tell a story from the perspective of a crafting table witnessing the creations of various players.",
        "Write a narrative from the point of view of a minecart journeying through expansive rail systems.",
        "Compose a tale where the wind narrates its travels across different Minecraft biomes and the changes it observes.",
        "Describe the experiences of a mountain over time as players mine and build upon it.",
        "Write a monologue from a Minecraft creeper's perspective, explaining its actions and desires.",
        "Compose a diary entry of a pillager planning an attack on a nearby village in Minecraft.",
        "Narrate the experiences of a beginner learning the ropes and making their first shelter before nightfall in a challenging game of Minecraft.",
        "Write a memoir of a seasoned Minecraft player sharing tips and stories from their extensive adventures.",
        "Tell a story about a Minecraft librarian uncovering ancient texts that reveal secrets of the world.",
        "Compose a narrative focusing on an artisan who creates intricate designs with banners and dyed wool in Minecraft.",
        "Write a series of letters between a player and their in-game friend, documenting their cooperative projects in Minecraft.",
        "Compose correspondence between Minecraft villagers discussing the impact of players on their daily lives.",
        "Create journal entries of a player's expedition to locate and conquer all the game's dungeons in Minecraft.",
        "Write a diary from the perspective of a player documenting their progress in mastering Redstone engineering in Minecraft.",
        "Draft a script for a reality TV show set in Minecraft, where contestants compete in building challenges.",
        "Write a script for a radio drama about a mysterious signal coming from the deepest caves.",
        "Compose an instruction manual on how to survive your first night in Minecraft, written for absolute beginners.",
        "Write a technical guide explaining advanced potion brewing techniques in Minecraft.",
        "Create a series of blog posts from a player sharing their journey to build a scale model of a real-world monument in Minecraft.",
        "Draft imaginary social media updates from a character discovering rare items and achievements in Minecraft.",
        "Write a Minecraft story about a player grappling with the decision to use cheats in the game, weighing fun against fairness.",
        "Compose a narrative exploring a player's guilt after accidentally triggering a raid on a village in Minecraft.",
        "Craft a philosophical dialogue between a player and an NPC about the meaning of existence in a procedurally generated world of Minecraft.",
        "Write a monologue where a character contemplates the endless cycle of creation and destruction in Minecraft.",
        "Describe a player's trepidation as they prepare to enter a newly discovered dimension with unfamiliar dangers in a Minecraft world.",
        "Compose a horror story set in a Minecraft world about unexplained phenomena occurring in what was thought to be a safe base.",
        "Write a comedic piece about a player's series of unfortunate events, such as repeatedly falling into their own traps in Minecraft.",
        "Compose a satirical obituary for a player's favorite pet who met an untimely end due to Minecraft game glitches.",
        "Draft a sarcastic essay titled \"The Joys of Lava Swimming: A Guide to Instant Respawn in Minecraft.\"",
        "Write an ironic advertisement promoting the benefits of building houses out of dirt blocks in Minecraft.",
        "Create a Minecraft parody of \"Star Wars,\" such as \"Block Wars: The Redstone Strikes Back.\"",
        "Write a spoof combining Minecraft with \"Harry Potter,\" featuring a school of crafting and magic.",
        "Tell a story inspired by Ragnarok, where the Minecraft world faces a great cataclysm brought on by powerful mobs.",
        "Write about a player undertaking quests similar to the Labors of Hercules within the Minecraft setting.",
        "Compose a story where players discover portals to alternate Minecraft worlds, each with its own rules and physics.",
        "Write about a glitch that merges multiple servers, causing chaos and new alliances in Minecraft.",
        "Draft an article announcing a breakthrough in Redstone technology that allows for instantaneous communication across the Minecraft world.",
        "Write a story about Minecraft players collaborating to build a massive, fully automated city powered by Redstone.",
        "Compose lyrics for a Minecraft-themed ballad about the perils of the Nether.",
        "Describe an in-game theater production where players reenact famous plays using Minecraft mechanics.",
        "Write a story based on Native American legends, featuring a Minecraft spirit animal guiding a player.",
        "Compose a tale inspired by Middle Eastern folklore, where a player seeks hidden treasures guarded by mythical creatures with a Minecraft theme.",
        "Describe a Minecraft celebration of Holi, incorporating vibrant colors and community events.",
        "Write about Minecraft characters observing the tradition of Thanksgiving within the game, including feasts and gratitude.",
        "Craft a story where players must use knowledge of chemistry to brew potions and solve puzzles in Minecraft.",
        "Write an adventure that teaches history by recreating significant historical landmarks and events in Minecraft.",
        "Compose dialogues where characters teach each other phrases in different languages to overcome communication barriers during multiplayer sessions in Minecraft.",
        "Write about a Minecraft player who uses building projects to manage stress and find calmness.",
        "Compose a reflective piece on practicing mindfulness while exploring serene biomes like forests and oceans in Minecraft.",
        "Tell a story about players establishing a wildlife reserve to protect rare mobs like ocelots and pandas in Minecraft.",
        "Draft a guide on creating sustainable energy sources in Minecraft using Redstone and other in-game resources.",
        "Write a Minecraft strategy guide inspired by Sun Tzu's The Art of War, focusing on understanding your enemy and using the terrain to your advantage.",
        "Describe how Napoleon Bonaparte would organize and execute a rapid conquest of neighboring Minecraft villages, emphasizing speed and decisive action.",
        "Compose a plan detailing how Alexander the Great would unify multiple Minecraft factions under one banner, promoting cooperation and shared goals.",
        "Narrate a story where Hannibal Barca leads a surprise attack in Minecraft by navigating through a perilous mountain biome to outflank an opponent.",
        "Explain how Erwin Rommel's tactics of mobile warfare could be applied using horses and minecarts for swift movements in Minecraft battles.",
        "Draft a Minecraft battle strategy utilizing George S. Patton's aggressive offense to clear out a Nether fortress filled with hostile mobs.",
        "Detail how Dwight D. Eisenhower would plan a large-scale coordinated attack on the Ender Dragon, focusing on logistics and teamwork among players.",
        "Write about Julius Caesar's approach to building infrastructure in Minecraft, including roads and bridges to improve movement and trade.",
        "Explain how Miyamoto Musashi's principles from The Book of Five Rings can be used to master close combat and archery in Minecraft.",
        "Compose an essay on applying Carl von Clausewitz's concept of the \"fog of war\" to Minecraft, emphasizing the unpredictability of exploration and combat.",
        "Describe how Genghis Khan would manage a Minecraft clan, focusing on horse-mounted combat and psychological tactics to dominate the server.",
        "Write a Minecraft conquest plan inspired by Attila the Hun, emphasizing fearsome reputation and swift raids on enemy bases.",
        "Explain how Hernán Cortés would navigate and exploit a new Minecraft biome, dealing with unfamiliar mobs and resources.",
        "Describe how King David would construct and defend a Minecraft fortress city, integrating strategic defense with moral leadership.",
        "Write a story where Joan of Arc inspires other players in Minecraft to rally against a powerful enemy, guided by her visions and courage.",
        "Compose a Minecraft guide on peaceful coexistence and community building based on Gautama Buddha's teachings.",
        "Explain how Mohandas Gandhi would resolve conflicts in Minecraft through non-violent methods, such as peaceful protests or hunger strikes in-game.",
        "Write about Saladin's strategies for reclaiming a Minecraft stronghold, emphasizing honor, respect for adversaries, and tactical brilliance.",
        "Compose a Minecraft manual inspired by Sun Tzu, focusing on the use of deception with hidden traps and secret passages.",
        "Explain how the strategic teachings of Miyamoto Musashi can help players balance offensive and defensive techniques in Minecraft combat.",
        "Write a guide on employing psychological tactics in Minecraft PvP, such as feints, taunts, and misinformation.",
        "Describe methods for using in-game chat and signs to confuse or mislead opponents, drawing parallels to historical deception strategies.",
        "Compose a treaty between Minecraft factions inspired by the Peace of Westphalia, outlining terms for coexistence and trade agreements.",
        "Explain strategies for building alliances in Minecraft, including mutual defense pacts and resource-sharing agreements.",
        "Write about optimizing resource gathering and storage in Minecraft, inspired by Julius Caesar's logistical strategies during his campaigns.",
        "Describe how to manage a sustainable food supply for large Minecraft settlements, drawing from historical siege preparations.",
        "Compose a guide on adapting building designs to different Minecraft biomes, inspired by Alexander the Great's adaptability in diverse terrains.",
        "Explain how to adjust tactics when facing unexpected threats like sudden mob swarms, using lessons from Erwin Rommel's flexible strategies.",
        "Write about constructing a Minecraft fortress using the principles of medieval castle architecture, including moats, battlements, and drawbridges.",
        "Describe setting up layered defenses in Minecraft, inspired by the Roman Legion's fortification methods."
        "Write a Minecraft parable inspired by the teachings of Jesus, conveying a moral lesson about cooperation and kindness among players.",
        "Describe how Prophet Muhammad would unify rival Minecraft factions through strategic alliances and fair governance, promoting peace and community building.",
        "Compose a narrative where Moses leads a group of players out of a perilous Nether landscape, emphasizing leadership and overcoming obstacles.",
        "Explain how Confucius's principles of social harmony and respect could be applied to manage a Minecraft community or server.",
        "Write about Laozi's concept of Wu Wei (non-action) and how it could influence a player's approach to resource management and conflict avoidance in Minecraft.",
        "Describe how Cyrus the Great would administer a vast Minecraft empire, focusing on respect for different cultures and effective governance.",
        "Compose a strategy guide based on Suleiman the Magnificent's administrative reforms, optimizing resource allocation and infrastructure in Minecraft settlements.",
        "Explain how Shaka Zulu's military innovations could be adapted for Minecraft combat tactics and team coordination.",
        "Write a story where William the Conqueror establishes a new order in a Minecraft world, implementing systems of governance and land management.",
        "Describe Queen Boudica's uprising against a dominant Minecraft faction, focusing on guerrilla tactics and rallying support from other players.",
        "Compose a Minecraft guide on power dynamics and strategy inspired by Niccolò Machiavelli's The Prince, including advice on leadership and maintaining control.",
        "Write a dialogue using the Socratic method, where a player helps another understand complex Redstone mechanics through questioning.",
        "Explain how Plato's concept of the ideal state could influence the design of a utopian Minecraft city, including governance and social structure.",
        "Compose a treatise on ethical decision-making in Minecraft based on Aristotle's virtues, balancing personal gain with community well-being.",
        "Write a speech inspired by Martin Luther King Jr., where a player advocates for fair play and equality on a multiplayer Minecraft server."
    ]

def next_action_preprompt():
    options = [
        "Based on my analysis above, the next predicted action would be",
        "Given the evaluation earlier, the following step should be",
        "Considering my critique, the next logical move is",
        "From the assessment above, the subsequent action would be",
        "Taking into account my analysis, the next step is",
        "In light of the above analysis, the next action should be",
        "As per my evaluation, the next predicted action is",
        "Reflecting on my findings, the next course of action would be",
        "Based on the discussion earlier, the next step should be",
        "Given the previous analysis, the next logical action is",
        "Considering the critique above, the following move would be",
        "From my review, the next action should be",
        "Taking my assessment into account, the next step would be",
        "In view of the analysis, the subsequent action is",
        "As a result of my evaluation, the next move should be",
        "Based on what I've analyzed, the next action would be",
        "Given my findings, the next logical step is",
        "Considering the above, the next predicted action should be",
        "From the prior analysis, the following action would be",
        "Taking into consideration my critique, the next step is",
        "In accordance with my assessment, the next action would be",
        "Reflecting on the evaluation, the next move should be",
        "Based on the analysis provided, the subsequent action is",
        "Given the assessment above, the next logical move would be",
        "Considering my findings, the next step should be",
        "From the critique earlier, the next predicted action is",
        "Taking into account the evaluation, the next action would be",
        "In light of my review, the following step should be",
        "As per the analysis above, the next move is",
        "Based on my assessment, the next logical action would be",
        "Given the discussion earlier, the next action should be",
        "Considering the evaluation, the next step is",
        "From my analysis, the subsequent action would be",
        "Taking into account my findings, the next move should be",
        "In view of the critique, the next predicted action is",
        "Reflecting on the assessment, the next logical step would be",
        "Based on the above analysis, the next action is",
        "Given my critique, the following action should be",
        "Considering the review, the next step would be",
        "From the findings above, the next move is",
        "Taking into consideration the analysis, the next action should be",
        "In accordance with the evaluation, the subsequent step would be",
        "As a result of my assessment, the next logical action is",
        "Based on what has been analyzed, the next step should be",
        "Given the findings, the next predicted action would be",
        "Considering the prior analysis, the next move is",
        "From my evaluation, the following action should be",
        "Taking my critique into account, the next step would be",
        "In light of the review, the next action is",
        "As per my findings, the next logical move should be",
        "Based on the assessment above, the next action would be",
        "Given the analysis provided, the next step is",
        "Considering my assessment, the subsequent action should be",
        "From the critique earlier, the next logical action is",
        "Taking into account the findings, the next move would be",
        "In view of the evaluation, the following step should be",
        "Reflecting on the analysis, the next action would be",
        "Based on my review, the next predicted action is",
        "Given the prior critique, the next step should be",
        "Considering the findings, the next logical move is",
        "From the assessment, the subsequent action should be",
        "Taking into consideration the evaluation, the next action is",
        "In accordance with my analysis, the next step would be",
        "As a result of the critique, the next move should be",
        "Based on what has been evaluated, the next action is",
        "Given my review, the following action would be",
        "Considering the analysis above, the next step should be",
        "From my findings, the next logical action is",
        "Taking into account the prior assessment, the next move would be",
        "In light of the critique, the subsequent action should be",
        "As per the evaluation, the next action is",
        "Based on the findings above, the next predicted step would be",
        "Given the assessment, the next logical move is",
        "Considering my evaluation, the next action should be",
        "From the review, the following step is",
        "Taking my analysis into account, the next move should be",
        "In view of the findings, the next action would be",
        "Reflecting on the critique, the next step should be",
        "Based on the prior analysis, the subsequent action is",
        "Given my assessment, the next predicted action would be",
        "Considering the evaluation above, the next move is",
        "From the findings, the next logical step should be",
        "Taking into consideration the critique, the next action would be",
        "In accordance with the review, the following step is",
        "As a result of the analysis, the next move should be",
        "Based on what has been found, the next action is",
        "Given the prior evaluation, the next step would be",
        "Considering the assessment, the next logical action is",
        "From my critique, the subsequent action should be",
        "Taking into account the review, the next move would be",
        "In light of the findings, the next action should be",
        "As per my analysis, the next predicted step is",
        "Based on the evaluation, the next action would be",
        "Given my findings, the following step should be",
        "Considering the critique above, the next move is",
        "From the assessment, the next logical action would be",
        "Taking into account my evaluation, the next step should be",
        "In view of the analysis, the subsequent action would be",
        "Reflecting on my findings, the next move is",
        "Based on the discussion, the next action should be",
        "Given the analysis above, the next predicted action is",
        "Considering the evaluation, the next step would be",
        "From my assessment, the following action should be",
        "Taking into consideration the findings, the next move is",
        "In accordance with the critique, the next action would be",
        "As a result of the evaluation, the next step should be",
        "Based on what has been analyzed, the subsequent action is",
    ]
    return random.choice(options)